default: &default
  adapter: postgresql
  encoding: utf8
  pool: 20
  database: blog_api_production
  username: blog_api
  password: 123456
  host: localhost

development:
  <<: *default
  database: blog_api_development

test:
  <<: *default
  database: blog_api_test

production:
  <<: *default
  database: blog_api_production
  username: blog_api
  password: <%= ENV['BLOG_API_DATABASE_PASSWORD'] %>
